language: rust

install:
  - CLIPPY_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/clippy)
  - echo "Latest nightly with Clippy is $CLIPPY_NIGHTLY"
  - rustup set profile minimal
  - rustup default "$CLIPPY_NIGHTLY"
  - rustup component add clippy

before_script:
  - git clone https://github.com/serde-rs/serde

script:
    # The need for -Aredundant_field_names here is a Clippy bug.
    # https://github.com/rust-lang/rust-clippy/issues/5356
  - cd "${TRAVIS_BUILD_DIR}/serde/serde"
  - cargo clippy --features rc,unstable -- -D clippy::all -A clippy::redundant_field_names
  - cd "${TRAVIS_BUILD_DIR}/serde/serde_derive"
  - cargo clippy -- -D clippy::all
  - cd "${TRAVIS_BUILD_DIR}/serde/serde_test"
  - cargo clippy -- -D clippy::all -A clippy::redundant_field_names
  - cd "${TRAVIS_BUILD_DIR}/serde/test_suite"
  - cargo clippy --tests --features unstable -- -D clippy::all -A clippy::redundant_field_names
  - cd "${TRAVIS_BUILD_DIR}/serde/test_suite/no_std"
  - cargo clippy -- -D clippy::all -A clippy::redundant_field_names
